version: '3.7'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - './portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '9000:9000'
